# Generated by Django 3.2.8 on 2021-11-16 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20211106_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='PESEL',
            field=models.CharField(default='', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Zły format PESELU: 11 cyfr!', regex='^[0-9]{11}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Zły format emailu: email@email', regex='^([-!#-\'*+\\-9=?A-Z^-~]+(\\.[-!#-\'*+\\-9=?A-Z^-~]+)*|"([]!#-[^-~ \t]|(\\[\t -~]))+")@([-!#-\'*+\\-9=?A-Z^-~]+(\\.[-!#-\'*+\\-9=?A-Z^-~]+)*|\\[[\t -Z^-~]*])$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Zły format PESELU: 9 cyfr!', regex='^[0-9]{9}$')]),
        ),
    ]
