# Generated by Django 3.2.8 on 2021-11-16 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Zły format numeru telefonu: 9 cyfr!', regex='^[0-9]{9}$')]),
        ),
    ]
