# Generated by Django 3.2.6 on 2021-08-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_books',
            field=models.IntegerField(default=5),
        ),
    ]
