# Generated by Django 3.2.6 on 2021-08-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_number_of_books_book_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ManyToManyField(to='API.Book'),
        ),
    ]
