# Generated by Django 3.2.6 on 2021-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210823_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(to='API.Books'),
        ),
    ]
