# Generated by Django 3.2.8 on 2021-11-13 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20211109_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 15)),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 13)),
        ),
    ]
