# Generated by Django 3.2.8 on 2021-11-13 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20211113_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number_of_apartment',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2021, 11, 15)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.deliverer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(default=datetime.date(2021, 12, 13)),
        ),
    ]
