# Generated by Django 3.2.8 on 2021-11-13 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20211113_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number_of_apartment',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 15)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 13)),
        ),
    ]
