# Generated by Django 3.2.8 on 2021-11-15 19:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20211113_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Zły format kodu pocztowego: XX-XXX (cyfry)', regex='^\\d{2}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 17)),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 15)),
        ),
    ]
