# Generated by Django 3.2.8 on 2021-11-16 15:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20211115_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Zły format miasta: Tylko litery', regex='^[a-zA-ZŻŹĆĄŚĘŃŁÓżźćąśęńłó]$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_of_apartment',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Zły format nr. lokalu: tylko cyfry XXXXX', regex='^[0-9]{1,5}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_of_building',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Zły format nr. budynku: tylko cyfry XXXXX', regex='^[0-9]{1,5}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Zły format powiaty: Tylko litery', regex='^[a-zA-ZŻŹĆĄŚĘŃŁÓżźćąśęńłó]$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Zły format ulicy: Tylko litery', regex='^[a-zA-ZŻŹĆĄŚĘŃŁÓżźćąśęńłó]$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 18)),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 16)),
        ),
    ]
