# Generated by Django 3.2.8 on 2021-11-16 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20211116_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Zły format miasta: Tylko litery', regex='^[a-zA-ZŻŹĆĄŚĘŃŁÓżźćąśęńłó ]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Zły format powiaty: Tylko litery', regex='^[a-zA-ZŻŹĆĄŚĘŃŁÓżźćąśęńłó ]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Zły format ulicy: Tylko litery', regex='^[a-zA-ZŻŹĆĄŚĘŃŁÓżźćąśęńłó ]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
