# Generated by Django 3.2.9 on 2021-11-29 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20211123_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 1)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 11, 29)),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 29)),
        ),
    ]
