# Generated by Django 3.2.9 on 2021-11-29 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20211129_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order_create',
            field=models.DateTimeField(blank=True, verbose_name=datetime.date(2021, 11, 29)),
        ),
    ]
