# Generated by Django 3.2.9 on 2021-11-30 15:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_order_date_order_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Zły format powiaty: Tylko litery', regex='^[a-zA-ZŻŹĆĄŚĘŃŁÓżźćąśęńłó- ]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 2)),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 30)),
        ),
    ]
